name: 'HTML Image Sizes'
description: 'Updates HTML image references with the height and width of the image.'

inputs:
  path:
    description: 'The directory containing the static website'
    required: true
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Update HTML image sizes
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js '${{ inputs.path }}'
